# nome da pipeline
name: Run Basic Testes

# em que momento será executada
on:
  pull_request:
    braches: [main]

    jobs:
    # o que vai ser feito nessa pipeline
    # só teremos um job: rodar os testes
      cypress-run:
        # maquina que será executado
        runs-on: ubuntu-latest

        # passo a passo para rodar os testes
        steps:
        # clone do projeto
        - name: Checkout
          uses: actions/checkout@v4

          # exemplo de execução no terminal
          - name: instalar dependencias do projeto
            run: npm start

          # execução e configuração do projeto
          - name: Cypress run
            uses: cypress-io/github-action@v6
            with:
              record: true
            env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}